### ISSUE TITLE
How to update the extensions?

### ISSUE THREAD

**Issue by BobWs** [JokerQyou/snextensions#11]
Hi,
I'm using a fork of your extension to selfhost with netlify and I was wondering how to update the extensions to their latest versions? Or is this done automatically?
TIA

**Comment by JokerQyou** [comment]
Use the update script: `python update.py`. After that you should build and deploy again.

**Comment by BobWs** [comment]
Hello,
I'm sorry to bother you again but I still have a question about updating the extensions. I used the update script as you suggested and rebuilt the site, but the extensions are not updated.

For example, the Bold-editor shows version 1.0.9 as before. But the current version is 1.1.0.
https://github.com/standardnotes/bold-editor/releases/tag/1.1.0

Am I doing something wrong? Or is it not possible to update the extensions this way to the latest versions?

**Comment by JokerQyou** [comment]
Sorry but I did not see that you are hosting with Netlify. With Netlify your site is built against the git repository, so you should commit the updated TOML files via git. As you can see from [here](https://github.com/JokerQyou/snextensions/commit/d3139b475a5b050d61da3d49d73693013f8cbf6b#diff-0297ea2d0577b031a53aced690e1bdc4) it is updated to `1.1.0`.

**Comment by BobWs** [comment]
Thanks I have managed to update my repo. Now I know how to do it for any future updates.
