### ISSUE TITLE
Need to change "identifiers" in JSON to Avoid SN blocking extensions for Subscription

### ISSUE THREAD

**Issue by twizzayy** [JokerQyou/snextensions#13]
I noticed that the Secure Spreadsheets extension is getting blocked by Standard Notes subscription requirements.
[See issue #789](https://github.com/standardnotes/forum/issues/789)
[And Issue #1550](https://github.com/standardnotes/forum/issues/1550)

The "Identifier" in the JSON file for the repo needs to be changed from `org.standardnotes.xxxx` to something else.

Also Extension repos are being [depreciated](https://github.com/standardnotes/forum/issues/1550#issuecomment-1062077943) by SN.

This means that in order to add extensions in newer versions they either need to be added one at a time using the individual extension JSON files, or people need to install an older version (I tested with [v.3.8.0](https://github.com/standardnotes/desktop/releases?page=5)) and then add the repo as instructed in your READme and *then* upgrade to the current version.

For self-hosters the best way to keep standard notes happy seems to be to stick with an older version for now.

**Comment by JokerQyou** [comment]
I've roughly read the referred threads, and it seems that extensions in general are being deprecated and being removed from the ecosystem (except for themes and editors), is that right?

I'm not current a daily StandardNotes user (I use it only occasionally), but I'll take a look when I get the time, probably next weekends. PRs are always welcome, though.

**Comment by twizzayy** [comment]
That's correct. They are becoming native features to the application. I think this is eventually planned for themes and editors too.

I think it's worth mentioning that these external repositories still work for older versions of Standard Notes for those users who don't mind staying a few generations behind. This isn't ideal, though...

I don't know the language, otherwise I would work on it myself. Thanks for providing this. :)

**Comment by twizzayy** [comment]
https://docs.standardnotes.com/self-hosting/subscriptions/
