### ISSUE TITLE
Selfhost extensions

### ISSUE THREAD

**Issue by alexkutsan** [JokerQyou/snextensions#3]
Is there some instruction to host snextensions on own server? 
Should I use `build.sh`?  How can I host it? What prerequisites?

**Comment by JokerQyou** [comment]
Hi @alexkutsan, I've updated the repo to contain self-hosting instructions [here](https://github.com/JokerQyou/snextensions/tree/bd140b964d6f417aeb3751d10b5afbe48affe11d#self-hosting), please have a look.
Feel free to comment if you have more questions.

**Comment by alexkutsan** [comment]
Thanks for the quick answer! It works :-) I had no experience with netfly before. Looking into it and still searching to the ability to make it fully self-hosted.

**Comment by JokerQyou** [comment]
I've also updated the README to contain self-hosting instructions without using Netlify. However it requires manual hosting of generated static resource files, and could vary greatly for different web server. So I can only cover the build instructions.

Should you need any further help, please do not hesitate to reopen this issue.
