### ISSUE TITLE
After changing the Site name in something readable the extensions don’t work anymore

### ISSUE THREAD

**Issue by BobWs** [JokerQyou/snextensions#7]
Hi,
I followed your steps as described to create a Netlify account and deploy the site. After this is successfully done I have tested it with SN and it was working, I could install the extensions and is was working on different devices.

But the problem arises when I change the name off the site in Netify into something better readable. I tried the new link with a new account I have created in standardnotes and I can install the extensions and I see them in the app menu, but I cannot created and write any notes. I keep seeing an error message “not found”

![0D763FC8-7E2B-4AC6-9306-3E695F458CE7](https://user-images.githubusercontent.com/5485820/90334859-dc462e80-dfd0-11ea-85a9-89bd2902d65e.jpeg)

To test my theory I deleted the site with the readable name from Netlify and created a new one. This time I didn’t change the name and used the auto generated link in Standardnotes to install the extensions, and it is working as should. 

So I’m wondering what is going wrong when changing the name for it not to work?

**Comment by JokerQyou** [comment]
Thanks for the report! I've not yet tested changing the sitename of Netlify site. I'll test it tonight (GMT+8) and investigate a little more.

**Comment by JokerQyou** [comment]
There are several issues regarding sitename changing:

- When you first setup the site with Netlify, the site URL is written to the JSON description of **each plugins** by the build script.
- When SN app load a plugin, the browser checks CORS rules of given resource URL.
- When you change the sitename, the site URL remains unchanged in the JSON description of each plugins.
- Now when SN app load a plugin via the new site URL, the plugin's JSON description tells it to load resources from the old site URL, which is now invalid.

You can manually trigger a deployment, which will run the build script again so the resource URLs of each plugins can be updated to the new site URL. You can do so via the Netlify web UI: go to your site > Deploys, on the top right corner of your deploys list, click Trigger Deploy > Clear cache and deploy site.

<img width="292" alt="Picture" src="https://user-images.githubusercontent.com/1465267/90350581-32b67a00-e070-11ea-9134-88d0d4c268e4.png">

**Comment by BobWs** [comment]
Okay thanks for explaining I will give it a try.

**Comment by BobWs** [comment]
Thanks it worked!
Maybe an idea to add this to the readme section?

**Comment by JokerQyou** [comment]
The README has been updated.
