### ISSUE TITLE
Can you add FileSafe-bar to the extensions repo?

### ISSUE THREAD

**Issue by BobWs** [JokerQyou/snextensions#8]
Hi,
Can you add FileSafe-bar to the extensions repo?
https://github.com/standardnotes/filesafe-bar

I should look like something like this when it is added
![561BB566-1C11-4D01-BE8E-461E197D02F2](https://user-images.githubusercontent.com/5485820/90973749-33925480-e525-11ea-8d18-62804b075e38.jpeg)

**Comment by JokerQyou** [comment]
Thanks for the info, I'll take a look later.

**Comment by JokerQyou** [comment]
I've added the FileSafe extension, however I've not used it, and I think it requires self-hosting the server part to work, see [this comment](https://github.com/standardnotes/forum/issues/503#issuecomment-475967285). Data care is at the core of StandardNotes' business model, so I don't expect any detailed documentation.
