### ISSUE TITLE
Can you add MFA-link?

### ISSUE THREAD

**Issue by jayknyn** [JokerQyou/snextensions#9]
Hi, thanks for your efforts here. 

Can you add the MFA-link extension: 
https://github.com/sn-extensions/mfa-link

**Comment by JokerQyou** [comment]
Hi, sorry for the late response, I'll take a look at this extension.

**Comment by JokerQyou** [comment]
This extension has been added and you can test it now. Should you run into any problames with it, please don't hesitate to comment here.
